# Generated by Django 4.2.7 on 2023-12-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.TextField()),
                ('descripcion', models.TextField()),
                ('talle', models.TextField()),
                ('cantidad_en_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='anteojos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('color', models.TextField()),
                ('cantidad_en_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('prenda', models.TextField()),
                ('descripcion', models.TextField()),
                ('talle', models.TextField()),
                ('cantidad_en_stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='buzos',
        ),
        migrations.DeleteModel(
            name='pantalones',
        ),
        migrations.DeleteModel(
            name='remeras',
        ),
    ]
